### ISSUE TITLE
Баг: при загрузке по URL задания не отображаются вкладки без перезагрузки

### ISSUE THREAD

**Issue by kushedow** [JadeRemi/standard-data-ide#1]
Как воспроизвести:

Перейти в тренажер
Вставить в желтельное поле ссылку https://fastapi-cors-proxy-1.onrender.com/api/api/tstask/3/
Нажать Load

Ожидание:
В левой панели появится вкладка index.ts
Остальные вкладки скроются

Реальность:
В левой панели вкладка появляется только после перезагрузки страницы
Лишние вкладки не исчезают никогда.

**Comment by JadeRemi** [comment]
done
